Add X-Ray support
micronaut-projects/micronaut-aws pull request #1008
Opened 2021-03-30 14:02 UTC by pgressa

Adds support for X-Ray tracing. Handles:
- incoming / outgoing http requests
- SDK Clients tracing interceptor
- cloudwatch metrics
- [in-progress] adds `AwsXRaySegment` and `AwsXRaySubsegment` method annotations

2021-04-23 16:37 UTC, sdelamo requested changes
The generated configuration properties documentation does not contain default values. 
<img width="1322" alt="Screenshot 2021-04-23 at 18 36 12" src="https://user-images.githubusercontent.com/864788/115902584-dd363680-a462-11eb-9f10-49ad54347a42.png">

2021-04-23 16:37 UTC, sdelamo commented on aws-xray/src/test/groovy/io/micronaut/tracing/aws/XRayConfigurationSpec.groovy
> +                "aws.xray.samplingRule": "rule"
Micronaut configuration is kebap case. 

This should be `aws.xray.sampling-rule`

2021-04-23 16:37 UTC, sdelamo commented on src/main/docs/guide/xray/xrayRecorder.adoc
> +Finally you can configure https://docs.aws.amazon.com/xray/latest/devguide/xray-console-sampling.html[the sampling rule] definition file using the configuration property `aws.xray.samplingRule`.
Micronaut configuration is kebap case. 

Instead of `aws.xray.samplingRule` it should be `aws.xray.sampling-rule`

2021-04-23 16:37 UTC, sdelamo commented on aws-xray/src/test/groovy/io/micronaut/tracing/aws/XRayConfigurationSpec.groovy
> +                "aws.xray.samplingRule": "rule"
I've changed this.

2021-04-23 16:37 UTC, sdelamo commented on src/main/docs/guide/xray/xrayRecorder.adoc
> +Finally you can configure https://docs.aws.amazon.com/xray/latest/devguide/xray-console-sampling.html[the sampling rule] definition file using the configuration property `aws.xray.samplingRule`.
I have changed this.

2021-04-23 17:28 UTC, sdelamo requested changes

2021-04-23 17:28 UTC, sdelamo commented on aws-xray/src/test/groovy/io/micronaut/tracing/aws/filter/XRayHttpClientFilterSpec.groovy
> +                "specName"                          : "XRayHttpClientFilterSpec"
We typically use `spec.name` instead of `specName`

2021-04-23 17:28 UTC, sdelamo commented on aws-xray/src/test/groovy/io/micronaut/tracing/aws/filter/XRayHttpClientFilterSpec.groovy
> +                "specName"                          : "XRayHttpClientFilterSpec"
We typically use `spec.name` instead of `specName`

2021-04-23 17:28 UTC, sdelamo commented on aws-xray/src/test/groovy/io/micronaut/tracing/aws/filter/XRayHttpClientFilterSpec.groovy
> +                "specName"                          : "XRayHttpClientFilterSpec"
We typically use `spec.name` instead of `specName`

2021-04-23 17:28 UTC, sdelamo commented on aws-xray/src/test/groovy/io/micronaut/tracing/aws/filter/XRayHttpClientFilterSpec.groovy
> +    @Requires(property = "specName", value = "XRayHttpClientFilterSpec")
We typically use `spec.name` instead of `specName`

2021-04-23 17:28 UTC, sdelamo commented on aws-xray/src/test/groovy/io/micronaut/tracing/aws/filter/XRayHttpServerFilterSpec.groovy
> +                "specName": "XRayHttpServerFilterSpec"
We typically use `spec.name` instead of `specName`

2021-04-23 17:28 UTC, sdelamo commented on aws-xray/src/test/groovy/io/micronaut/tracing/aws/filter/XRayHttpServerFilterSpec.groovy
> +                "specName": "XRayHttpServerFilterSpec"
We typically use `spec.name` instead of `specName`

2021-04-23 17:28 UTC, sdelamo commented on aws-xray/src/test/groovy/io/micronaut/tracing/aws/filter/XRayHttpServerFilterSpec.groovy
> +                "specName": "XRayHttpServerFilterSpec"
We typically use `spec.name` instead of `specName`

2021-04-23 17:28 UTC, sdelamo commented on aws-xray/src/test/groovy/io/micronaut/tracing/aws/filter/XRayHttpServerFilterSpec.groovy
> +                "specName": "XRayHttpServerFilterSpec"
We typically use `spec.name` instead of `specName`

2021-04-23 17:28 UTC, sdelamo commented on aws-xray/src/test/groovy/io/micronaut/tracing/aws/filter/XRayHttpServerFilterSpec.groovy
> +                "specName": "XRayHttpServerFilterSpec"
We typically use `spec.name` instead of `specName`

2021-04-23 17:28 UTC, sdelamo commented on aws-xray/src/test/groovy/io/micronaut/tracing/aws/filter/XRayHttpServerFilterSpec.groovy
> +    @Requires(property = "specName", value = "XRayHttpServerFilterSpec")
We typically use `spec.name` instead of `specName`

2021-04-23 17:38 UTC, sdelamo requested changes

2021-04-23 17:38 UTC, sdelamo commented on aws-xray/src/main/java/io/micronaut/tracing/aws/XRayRecorderFactory.java
> +@Requires(property = XRayConfiguration.PREFIX + ".enabled", notEquals = StringUtils.FALSE)
I think we have to add  `defaultValue = StringUtils.TRUE`

2021-04-23 17:38 UTC, sdelamo commented on aws-xray/src/main/java/io/micronaut/tracing/aws/client/SdkClientBuilderListener.java
> +@Requires(property = XRayConfiguration.PREFIX + "." + XRayConfiguration.SdkClientsConfiguration.PREFIX + ".enabled", notEquals = StringUtils.FALSE)
I think we have to add  `defaultValue = StringUtils.TRUE`

2021-04-23 17:38 UTC, sdelamo commented on aws-xray/src/main/java/io/micronaut/tracing/aws/cloudwatch/MetricsSegmentListenerFactory.java
> +@Requires(property = XRayConfiguration.PREFIX + "." + XRayConfiguration.XRayCloudWatchMetricsConfiguration.PREFIX + ".enabled", notEquals = StringUtils.FALSE)
I think we have to add  `defaultValue = StringUtils.TRUE`

2021-04-23 17:38 UTC, sdelamo commented on aws-xray/src/main/java/io/micronaut/tracing/aws/filter/XRayHttpClientFilter.java
> +@Requires(property = XRayConfiguration.PREFIX + "." + XRayConfiguration.XRayHttpFilterConfiguration.PREFIX + "." + XRayConfiguration.XRayHttpFilterConfiguration.XRayHttpClientFilterConfiguration.PREF
I think we have to add  `defaultValue = StringUtils.TRUE`

2021-04-23 17:38 UTC, sdelamo commented on aws-xray/src/main/java/io/micronaut/tracing/aws/filter/XRayHttpServerFilter.java
> +@Requires(property = XRayConfiguration.PREFIX + "." + XRayConfiguration.XRayHttpFilterConfiguration.PREFIX + "." + XRayConfiguration.XRayHttpFilterConfiguration.XRayHttpServerFilterConfiguration.PREF
I think we have to add  `defaultValue = StringUtils.TRUE`

2021-04-23 18:22 UTC, sdelamo commented on aws-xray/src/test/groovy/io/micronaut/tracing/aws/filter/XRayHttpClientFilterSpec.groovy
> +                "specName"                          : "XRayHttpClientFilterSpec"
I have done this change.

2021-04-23 18:22 UTC, sdelamo commented on aws-xray/src/test/groovy/io/micronaut/tracing/aws/filter/XRayHttpClientFilterSpec.groovy
> +                "specName"                          : "XRayHttpClientFilterSpec"
I have done this change.

2021-04-23 18:22 UTC, sdelamo commented on aws-xray/src/test/groovy/io/micronaut/tracing/aws/filter/XRayHttpClientFilterSpec.groovy
> +    @Requires(property = "specName", value = "XRayHttpClientFilterSpec")
I have done this change.

2021-04-23 18:22 UTC, sdelamo commented on aws-xray/src/test/groovy/io/micronaut/tracing/aws/filter/XRayHttpServerFilterSpec.groovy
> +                "specName": "XRayHttpServerFilterSpec"
I have done this change.

2021-04-23 18:22 UTC, sdelamo commented on aws-xray/src/test/groovy/io/micronaut/tracing/aws/filter/XRayHttpServerFilterSpec.groovy
> +                "specName": "XRayHttpServerFilterSpec"
I have done this change.

2021-04-23 18:22 UTC, sdelamo commented on aws-xray/src/test/groovy/io/micronaut/tracing/aws/filter/XRayHttpServerFilterSpec.groovy
> +    @Requires(property = "specName", value = "XRayHttpServerFilterSpec")
I have done this change.

2021-04-23 18:22 UTC, sdelamo commented on aws-xray/src/main/java/io/micronaut/tracing/aws/client/SdkClientBuilderListener.java
> +@Requires(property = XRayConfiguration.PREFIX + "." + XRayConfiguration.SdkClientsConfiguration.PREFIX + ".enabled", notEquals = StringUtils.FALSE)
I have done this change.

2021-04-23 18:23 UTC, sdelamo commented on aws-xray/src/main/java/io/micronaut/tracing/aws/filter/XRayHttpClientFilter.java
> +@Requires(property = XRayConfiguration.PREFIX + "." + XRayConfiguration.XRayHttpFilterConfiguration.PREFIX + "." + XRayConfiguration.XRayHttpFilterConfiguration.XRayHttpClientFilterConfiguration.PREF
I have done this change.

2021-04-23 18:23 UTC, sdelamo commented on aws-xray/src/main/java/io/micronaut/tracing/aws/filter/XRayHttpServerFilter.java
> +@Requires(property = XRayConfiguration.PREFIX + "." + XRayConfiguration.XRayHttpFilterConfiguration.PREFIX + "." + XRayConfiguration.XRayHttpFilterConfiguration.XRayHttpServerFilterConfiguration.PREF
I have done this change.

2021-04-23 18:23 UTC, sdelamo commented on aws-xray/src/main/java/io/micronaut/tracing/aws/cloudwatch/MetricsSegmentListenerFactory.java
> +@Requires(property = XRayConfiguration.PREFIX + "." + XRayConfiguration.XRayCloudWatchMetricsConfiguration.PREFIX + ".enabled", notEquals = StringUtils.FALSE)
I have done this change.

2021-04-23 18:23 UTC, sdelamo commented on aws-xray/src/main/java/io/micronaut/tracing/aws/XRayRecorderFactory.java
> +@Requires(property = XRayConfiguration.PREFIX + ".enabled", notEquals = StringUtils.FALSE)
I have done this change.

2021-04-23 18:23 UTC, sdelamo commented on aws-xray/src/test/groovy/io/micronaut/tracing/aws/filter/XRayHttpServerFilterSpec.groovy
> +                "specName": "XRayHttpServerFilterSpec"
I have done this change.

2021-04-23 18:23 UTC, sdelamo commented on aws-xray/src/test/groovy/io/micronaut/tracing/aws/filter/XRayHttpServerFilterSpec.groovy
> +                "specName": "XRayHttpServerFilterSpec"
I have done this change.

2021-04-23 18:23 UTC, sdelamo commented on aws-xray/src/test/groovy/io/micronaut/tracing/aws/filter/XRayHttpServerFilterSpec.groovy
> +                "specName": "XRayHttpServerFilterSpec"
I have done this change.

2021-04-23 18:24 UTC, sdelamo commented on aws-xray/src/test/groovy/io/micronaut/tracing/aws/filter/XRayHttpClientFilterSpec.groovy
> +                "specName"                          : "XRayHttpClientFilterSpec"
I have done this change.

2021-04-25 18:45 UTC, sdelamo commented
I have changed the package to `io.micronaut.aws.xray` so that it starts with `io.micronaut.aws`; the Maven coordinate group id. 

---

I have changed the configuration to be: 

`tracing.xray.*`. 

Other distributed tracing configuration uses `tracing` as the prefix. For example: `tracing.jaeger` or `tracing.zipkin`

---

I have created `package-info.java` files for each folder. I have used [@Configuration](https://docs.micronaut.io/latest/guide/#beanConfigurations) with `@Requires` in those files. 

---

I have simplified configuration so that it stays: 

|property |
|:--- |
|`xray.enabled`|
|`xray.segment-name`|
|`xray.server-filter`|
|`xray.client-filter`|
|`xray.sdk-clients`|
|`xray.cloud-watch-metrics`|

I have leverage the JavaDoc to show the default values in the documentation using the `configurationProperties` feature of our documentation. 

---

I will continue working on this PR to include it in 2.7.0

2021-04-25 18:52 UTC, graemerocher commented
Nice work guys

2021-04-25 18:57 UTC, sdelamo commented
Moreover, I want to check if we could use this library which is a bridge between XRay and Open Tracing 

https://github.com/opentracing-contrib/java-xray-tracer and maybe leverage Micronaut Tracing support.

2021-04-25 18:58 UTC, sdelamo commented
I've also removed the `@Requires( Environment.EC2)` X-Ray can be run on premise or on the developers laptop .Thus, I think it is more correct if we don't require the EC2 environment.

2021-09-07 12:26 UTC, sdelamo commented
I've started a guide: https://github.com/micronaut-projects/micronaut-guides/pull/508

and I think this is a blocker: https://github.com/micronaut-projects/micronaut-core/pull/6114

2021-09-09 05:45 UTC, sdelamo commented
This is another blocker: https://github.com/micronaut-projects/micronaut-core/pull/6127

2021-11-10 19:30 UTC, graemerocher commented
I got asked in the technical advisory board about the status of AWS X-Ray support, @sdelamo what is the status on this PR?

2021-11-11 11:04 UTC, sdelamo commented
> I got asked in the technical advisory board about the status of AWS X-Ray support, @sdelamo what is the status on this PR?

Still not finished. The scencario in this guide https://github.com/micronaut-projects/micronaut-guides/pull/508 which is the sample guide that we have for other distributed tracing solutions (jaeger, zipkin) is not working yet. I am revisiting this PR next.

2021-11-11 11:44 UTC, graemerocher commented
@sdelamo do you need assistance from @pgressa to resolve it?

2021-11-11 12:49 UTC, sdelamo commented
yeah, maybe that it is best. Maybe @pgressa can help me get this to the finish line

2021-11-16 10:16 UTC, sdelamo commented
@pgressa 

I have published a branch `xrayfilters` with some changes to handle reactive bodies. 

We have a guide scenario that we need to support: 

https://github.com/micronaut-projects/micronaut-guides/pull/508

## How to test that scenario. 

Publish this module to mavenLocal
 `./gradlew -x test pTMVL`

in the `micronaut-guides` repo. Branch `xrayguide`. 

Generate the guide projects:

`./gradlew -Dmicronaut.guide=micronaut-microservices-distributed-tracing-xray build`

these generates the three apps under `build/code/micronaut-microservices-distributed-tracing-xray-gradle-java`

This to see the guide locally: 

`open build/dist/index.html `

You have to configure the AWS Account with `aws configure` 

I run xray daemon locally

`./xray_mac -o -n us-east-1`

Run catalogue 

`cd build/code/micronaut-microservices-distributed-tracing-xray-gradle-java/bookcatalogue`
`./gradlew run`

Run bookinventory

`cd build/code/micronaut-microservices-distributed-tracing-xray-gradle-java/bookinventory`
`./gradlew run`

Run bookrecommendation 

`cd build/code/micronaut-microservices-distributed-tracing-xray-gradle-java/bookrecomendation`
`./gradlew run`


After, every service is running you can do: 

```
 curl http://localhost:8080/books
[{"name":"Building Microservices"}]
```

The goal is to see a tracing scenario such as the one we have in the zipkin guide.

<img width="1202" alt="zipkinui" src="https://user-images.githubusercontent.com/864788/141966761-b3ae73df-8551-4eb6-a56c-7a74aad38438.png">

2022-02-08 10:55 UTC, msailes commented
X-Ray 2.11.0 now supports GraalVM native-image. (It includes the resource and reflect config required.)

2022-02-19 15:13 UTC, timyates commented
Found this issue https://github.com/aws/aws-xray-java-agent/issues/87#issuecomment-792975052 which links to using opentelemetry as a gateway to xray https://aws-otel.github.io/docs/getting-started/java-sdk 

I wonder if that gets us where we want to be, as there doesn't seem to be much movement on a [non-thread-local xray client library](https://github.com/aws/aws-xray-sdk-java/issues/54)

2022-04-08 21:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/micronaut-projects/micronaut-aws?pullRequest=1008) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/micronaut-projects/micronaut-aws?pullRequest=1008) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: sdelamo<br/>:x: Pavol Gressa<br/><hr/>**Pavol Gressa** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/micronaut-projects/micronaut-aws?pullRequest=1008) it.</sub>

2022-09-02 14:18 UTC, graemerocher commented
now that we have open telemetry this is not needed

2022-09-02 14:18 UTC, closed without merging