Log context initialization errors
micronaut-projects/micronaut-aws pull request #1434
Opened 2022-08-09 09:31 UTC by musketyr

In case of using an external system to monitor errors such as Sentry there is currently no way how to forward context creation errors into the system. 

When there is an issue with the `ApplicationContext` such as missing property then the errors are only logged into CloudWatch which is not sufficient.

Logging the errors in the constructor where they initialization happens is the best way how to keep track of these issues.

2022-08-09 09:37 UTC, musketyr commented
I'm not sure how to resolve the code violations 🤷

2022-08-09 12:55 UTC, graemerocher commented
Take a look at the check style report which will provide some hints

2022-08-09 14:58 UTC, musketyr commented
I've seen it but it looks to me to report violations which have been there before the PR

2022-08-11 14:20 UTC, musketyr commented
@graemerocher fixed

2022-09-01 11:24 UTC, graemerocher requested changes

2022-09-01 11:24 UTC, graemerocher commented on function-aws/src/main/java/io/micronaut/function/aws/MicronautRequestHandler.java
> +            LOG.error("Exception initializing handler", e);
Perhaps include the message like: 

```java
 LOG.error("Exception initializing handler: " + e.getMessage(), e);
```

2022-09-02 06:33 UTC, musketyr commented on function-aws/src/main/java/io/micronaut/function/aws/MicronautRequestHandler.java
> +            LOG.error("Exception initializing handler", e);
done

2022-09-02 14:17 UTC, merged

2022-09-02 14:17 UTC, graemerocher commented
Thanks for the contribution!