Support multiple prefixes for aws distributed configuration
micronaut-projects/micronaut-aws pull request #1577
Opened 2023-01-17 21:58 UTC by marcin-majewski-sonarsource

I would like to suggest an addition to support multiple prefixes for micronaut AWS distributed configuration. The change is not breaking and the previous remains the same if the prefixes property is not set. 

The need it fulfills is the situation where the configuration has to be read from multiple secrets that do not share a common prefix. 

Let me know what you think.

2023-01-17 22:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/micronaut-projects/micronaut-aws?pullRequest=1577) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/micronaut-projects/micronaut-aws?pullRequest=1577) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/micronaut-projects/micronaut-aws?pullRequest=1577) it.</sub>

2023-01-18 10:20 UTC, alvarosanchez approved these changes

2023-01-23 09:47 UTC, marcin-majewski-sonarsource commented
@alvarosanchez do you know by any chance how can I proceed here? I can see that the sonar scan is failing due to the access to the SONAR_TOKEN secrets, I am pretty sure it is due to the fact, that secret are not propagated when running the action in the PR from the forked repository (looks to be a similar problem here: https://community.sonarsource.com/t/sonar-cannot-be-run-on-pr-from-a-fork/69229 and there are some workaround to be incorporated)

2023-01-23 10:25 UTC, alvarosanchez commented
@marcin-majewski-sonarsource don't worry, it's a known issue caused by what you linked. It's an optional check, nevertheless, so as long as the other check pass, it's fine.

I will proceed with merging, but there's one more thing I would like you to change.

2023-01-23 10:30 UTC, alvarosanchez requested changes

2023-01-23 10:30 UTC, alvarosanchez commented on aws-distributed-configuration/src/main/java/io/micronaut/aws/distributedconfiguration/AwsDistributedConfiguration.java
> +    List<String> getPrefixes();
Please add `since` tag pointing to `3.12.1`, and make it a `default` method that returns an empty list.

2023-01-23 10:30 UTC, alvarosanchez commented on aws-distributed-configuration/src/main/java/io/micronaut/aws/distributedconfiguration/AwsDistributedConfigurationProperties.java
> +    private List<String> prefixes = new ArrayList<>();
Annotate with `@NonNull`

2023-01-23 10:30 UTC, alvarosanchez commented on aws-distributed-configuration/src/main/java/io/micronaut/aws/distributedconfiguration/AwsDistributedConfiguration.java
>      String getPrefix();
Please, also mention in `getPrefix()` Javadoc that it will not be used if prefixes is set.

2023-01-26 17:20 UTC, marcin-majewski-sonarsource commented
@alvarosanchez my latest commit acknowledges the comments (I left the comments opened and will let you resolve, not sure what the process is here)

2023-01-27 09:59 UTC, merged