Improve logging
micronaut-projects/micronaut-aws pull request #1866
Opened 2023-09-01 14:23 UTC by sdelamo

ApplicationLoadBalancerRequestEvent and APIGatewayV2HTTPEvent uses Lombok @Data which applies toString https://projectlombok.org/features/Data

APIGatewayProxyRequestEvent overrides toString to render a JSON representation of the object

2023-09-01 14:31 UTC, timyates requested changes
Should we do `ApplicationLoadBalancerHandler` as well for ALB events?

`ApplicationLoadBalancerRequestEvent` also uses Lombok

Also, it's not json, it's just stuck between `{` and `}` for some reason 😉

2023-09-20 08:29 UTC, sdelamo commented
> Should we do `ApplicationLoadBalancerHandler` as well for ALB events?
> 
> `ApplicationLoadBalancerRequestEvent` also uses Lombok
> 
> Also, it's not json, it's just stuck between `{` and `}` for some reason 😉

I am logging in `ApplicationLoadBalancerHandler` as well. Is that what you meant?

2023-09-20 08:39 UTC, sdelamo commented on function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/alb/ApplicationLoadBalancerHandler.java
> +            LOG.info("Request: {}", request);
```suggestion
            LOG.trace("Request: {}", request);
```

2023-09-20 08:39 UTC, sdelamo commented on function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/payload2/APIGatewayV2HTTPEventHandler.java
> +            LOG.info("Request: {}", request);
```suggestion
            LOG.trace("Request: {}", request);
```

2023-09-20 08:39 UTC, sdelamo commented on function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/payload1/ApiGatewayProxyEventHandler.java
> +            LOG.info("Request: {}", request);
```suggestion
            LOG.trace("Request: {}", request);
```

2023-09-20 12:48 UTC, timyates approved these changes

2023-10-09 14:57 UTC, merged