Add SsmClient bean
micronaut-projects/micronaut-aws pull request #737
Opened 2020-11-19 19:02 UTC by ttzn

Having a bean to query the Parameter Store sounds useful. This should be a pretty painless MR. I'm marking this as WIP as I need to make a couple more checks but I'd like your opinion.

2020-11-23 07:12 UTC, graemerocher commented
Build is actually passing, we need to fix the test annotation thing

2020-11-23 09:30 UTC, alvarosanchez requested changes

2020-11-23 09:30 UTC, alvarosanchez commented on src/main/docs/guide/sdkv2/ssm.adoc
> +dependency:sqs[groupId="software.amazon.awssdk"]
```suggestion
dependency:ssm[groupId="software.amazon.awssdk"]
```

2020-11-23 10:11 UTC, alvarosanchez approved these changes

2020-12-05 04:38 UTC, sdelamo requested changes
Thanks for the contribution. Please, address the comments and I will merge the PR.

2020-12-05 04:38 UTC, sdelamo commented on aws-sdk-v2/src/test/groovy/io/micronaut/aws/sdk/v2/service/SsmClientSpec.groovy
> +class SsmClientSpec extends Specification{
please, add a trailing space. 

replace: `Specification{`

with `Specification {`

2020-12-05 04:38 UTC, sdelamo commented on aws-sdk-v2/src/test/groovy/io/micronaut/aws/sdk/v2/service/SsmClientSpec.groovy
> +        client.serviceName() == SsmClient.SERVICE_NAME
please, close the application context. Add: 

```groovy
cleanup: 
applicationContext.close()
```

2020-12-05 04:38 UTC, sdelamo commented on aws-sdk-v2/src/test/groovy/io/micronaut/aws/sdk/v2/service/SsmClientSpec.groovy
> +        client.serviceName() == SsmClient.SERVICE_NAME
please, close the application context. add: 

```groovy
cleanup: 
applicationContext.close()
```

2020-12-05 18:55 UTC, ttzn commented
@sdelamo I went all the way and improved all other tests in sdk-v2.

2020-12-14 09:01 UTC, sdelamo commented
thanks @ttzn 

I've moved the application context close in tests to https://github.com/micronaut-projects/micronaut-aws/pull/808

2020-12-14 09:04 UTC, sdelamo commented
Closed via: https://github.com/micronaut-projects/micronaut-aws/pull/810

2020-12-14 09:04 UTC, closed without merging